DROP TABLE IF EXISTS ACSDBO.ACS_POS_MONTHLY_CHAR;
DROP TABLE IF EXISTS ACSDBO.ACS_POS_MONTHLY_MPT_STATS;
DROP TABLE IF EXISTS ACSDBO.ACS_POS_TURNOVER;
DROP TABLE IF EXISTS PACE_MASTERDBO.BUSINESS_CALENDAR;